CREATE TABLE IF NOT EXISTS movies (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title TEXT NOT NULL,
	year INTEGER NOT NULL,
	runtime INTEGER NOT NULL,
	genres TEXT[] NOT NULL,
	version INTEGER NOT NULL DEFAULT 1,
	created_at TIMESTAMP NOT NULL DEFAULT now(),
	updated_at TIMESTAMP NOT NULL DEFAULT now()
);
