services:
  postgres:
    image: postgres:17.6-trixie
    container_name: movies-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
