// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID        int64            `json:"id"`
	Title     string           `json:"title"`
	Year      int32            `json:"year"`
	Runtime   int32            `json:"runtime"`
	Genres    []string         `json:"genres"`
	Version   int32            `json:"version"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
